# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/primoc/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/primoc/proprietary/lib/hw/camera.default.so:obj/lib/hw/camera.default.so \

# Audio Blobs
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/primoc/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \

# Camera
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
    vendor/htc/primoc/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/primoc/proprietary/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/primoc/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/primoc/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_default_video.so:system/lib/libchromatix_s5k4e5yx_default_video.so \
    vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hdr.so:system/lib/libchromatix_s5k4e5yx_hdr.so \
    vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hfr.so:system/lib/libchromatix_s5k4e5yx_hfr.so \
    vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hfr_4x.so:system/lib/libchromatix_s5k4e5yx_hfr_4x.so \
    vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_preview.so:system/lib/libchromatix_s5k4e5yx_preview.so \
    vendor/htc/primoc/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
    vendor/htc/primoc/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/primoc/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/primoc/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/primoc/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/htc/primoc/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so

# Ril
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/lib/libdll.so:/system/lib/libdll.so \
    vendor/htc/primoc/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/htc/primoc/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
    vendor/htc/primoc/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/primoc/proprietary/lib/libidl.so:/system/lib/libidl.so \
    vendor/htc/primoc/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/htc/primoc/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
    vendor/htc/primoc/proprietary/lib/libril.so:/system/lib/libril.so \
    vendor/htc/primoc/proprietary/lib/libqmi.so:/system/lib/libqmi.so

# Random Crap..Verify necessity 
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/primoc/proprietary/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/primoc/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/primoc/proprietary/bin/zcb:/system/bin/zcb \
    vendor/htc/primoc/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/htc/primoc/proprietary/lib/libgemini.so:/system/lib/libgemini.so
